server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    g-zip-content: true
spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      enabled: true
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    propagation:
      type: w3c
    baggage:
      enabled: true
    enabled: true
    sampling:
      probability: 1.0
